const eosData = [
  {
    id: 1,
    employeeId: 23001,
    employeeName: "John Doe",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project A",
    workPercentage: 80,
    remarks: "Good work",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 2,
    employeeId: 23002,
    employeeName: "Jane Smith",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project B",
    workPercentage: 60,
    remarks: "Needs improvement",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 3,
    employeeId: 23003,
    employeeName: "Alice Johnson",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project C",
    workPercentage: 100,
    remarks: "Excellent work",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 4,
    employeeId: 23004,
    employeeName: "Bob Williams",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project D",
    workPercentage: 75,
    remarks: "Satisfactory",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 5,
    employeeId: 23001,
    employeeName: "John Doe",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project B",
    workPercentage: 80,
    remarks: "Good work-2",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 6,
    employeeId: 23002,
    employeeName: "Jane Smith",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project C",
    workPercentage: 60,
    remarks: "Needs improvement-2",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 7,
    employeeId: 23003,
    employeeName: "Alice Johnson",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project D",
    workPercentage: 100,
    remarks: "Excellent work-2",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"Yes"
  },

  {
    id: 8,
    employeeId: 23004,
    employeeName: "Bob Williams",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project A",
    workPercentage: 75,
    remarks: "Satisfactory-2",
    approverRemarks: "",
    status: "",
    submitionDate: "25 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 9,
    employeeId: 23001,
    employeeName: "John Doe",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project C",
    workPercentage: 80,
    remarks: "Good work-3",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 10,
    employeeId: 23002,
    employeeName: "Jane Smith",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project D",
    workPercentage: 60,
    remarks: "Needs improvement-3",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 11,
    employeeId: 23003,
    employeeName: "Alice Johnson",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project A",
    workPercentage: 100,
    remarks: "Excellent work-3",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 12,
    employeeId: 23004,
    employeeName: "Bob Williams",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project B",
    workPercentage: 75,
    remarks: "Satisfactory-3",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 13,
    employeeId: 23001,
    employeeName: "John Doe",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project D",
    workPercentage: 80,
    remarks: "Good work-4",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 14,
    employeeId: 23001,
    employeeName: "John Doe",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project E",
    workPercentage: 80,
    remarks: "Good work-5",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 15,
    employeeId: 23002,
    employeeName: "Jane Smith",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project E",
    workPercentage: 60,
    remarks: "Needs improvement-4",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 16,
    employeeId: 23002,
    employeeName: "Jane Smith",
    projectName: "Project A",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    workPercentage: 60,
    remarks: "Needs improvement-5",
    approverRemarks: "",
    status: "",
    submitionDate: "25 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 17,
    employeeId: 23003,
    employeeName: "Alice Johnson",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project B",
    workPercentage: 100,
    remarks: "Excellent work-4",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 18,
    employeeId: 23003,
    employeeName: "Alice Johnson",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project E",
    workPercentage: 100,
    remarks: "Excellent work-5",
    approverRemarks: "",
    status: "",
    submitionDate: "26 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 19,
    employeeId: 23004,
    employeeName: "Bob Williams",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectName: "Project C",
    workPercentage: 75,
    remarks: "Satisfactory-4",
    approverRemarks: "",
    status: "",
    submitionDate: "26 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 20,
    employeeId: 23005,
    employeeName: "Ankit Kumar Thakur",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectManager: "AmritPreet Singh",
    projectName: "Project ",
    workPercentage: "",
    remarks: "",
    approverRemarks: "",
    status: "",
    submitionDate: "26 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 21,
    employeeId: 23006,
    employeeName: "Abhishek Kumar Thakur",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectManager: "AmritPreet Singh",
    projectName: "Project D",
    workPercentage: "",
    remarks: "",
    approverRemarks: "",
    status: "",
    submitionDate: "24 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 22,
    employeeId: 23007,
    employeeName: "Nikita Singh",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectManager: "AmritPreet Singh",
    projectName: "Project E",
    workPercentage: "",
    remarks: "",
    approverRemarks: "",
    status: "",
    submitionDate: "25 Jun 2024",
    pmApproval:"No"
  },
  {
    id: 23,
    employeeId: 23008,
    employeeName: "Anjali",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectManager: "AmritPreet Singh",
    projectName: "Project F",
    workPercentage: "",
    remarks: "",
    approverRemarks: "",
    status: "",
    submitionDate: "22 Jun 2024",
    pmApproval:"Yes"
  },
  {
    id: 24,
    employeeId: 23009,
    employeeName: "Arvind Singh",
    reportingManager: "Dhruv Kumar Saxena",
    projectManager: "AmritPreet Singh",
    projectManager: "AmritPreet Singh",
    projectName: "Project G",
    workPercentage: "",
    remarks: "",
    approverRemarks: "",
    status: "",
    submitionDate: "23 Jun 2024",
    pmApproval:"No"
  },
];

export { eosData };
