const projectDataWithMilestones = [
  {
    projectId: "P001",
    projectName: "Website Redesign",
    status: "In Progress",
    health: "Good",
    projectManager: "Alice Johnson",
    teams: ["Software", "Hardware", "FPGA", "QA", "Design"],
    description:
      "Redesigning company website to improve user experience and modernize the design.",
    plannedStartDate: "2024-06-01",
    plannedEndDate: "2024-12-31",
    actualStartDate: "2024-06-15",
    actualEndDate: null,
    client: "ABC Corporation",
    contactPerson: "John Smith",
    contactPersonPhone: "123-456-7890",
    contactPersonEmail: "john@example.com",
    history: ["Project kickoff meeting held on 2024-06-10."],
    milestones: [
      {
        milestoneId: "m1",
        name: "Planning Phase",
        description: "Define project scope and objectives.",
        dueDate: "2024-07-15",
        status: "Completed",
        tasks: [
          {
            taskId: "t1",
            name: "Gather requirements",
            description:
              "Meet with stakeholders to gather project requirements.",
            assignedTo: "Design",
            status: "Completed",
            dueDate: "2024-06-30",
          },
          {
            taskId: "t2",
            name: "Create wireframes",
            description: "Design wireframes for the new website layout.",
            assignedTo: "Design",
            status: "Completed",
            dueDate: "2024-07-05",
          },
        ],
      },
      {
        milestoneId: "m2",
        name: "Development Phase",
        description: "Build and implement new website features.",
        dueDate: "2024-09-30",
        status: "In Progress",
        tasks: [
          {
            taskId: "t3",
            name: "Frontend Development",
            description: "Implement frontend components based on wireframes.",
            assignedTo: "Software",
            status: "In Progress",
            dueDate: "2024-08-15",
          },
          {
            taskId: "t4",
            name: "Backend Development",
            description:
              "Develop backend functionality for user authentication and data management.",
            assignedTo: "Software",
            status: "Pending",
            dueDate: "2024-08-30",
          },
        ],
      },
      {
        milestoneId: "m3",
        name: "Testing Phase",
        description: "Perform testing and quality assurance.",
        dueDate: "2024-11-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Deployment Phase",
        description: "Deploy the redesigned website to production.",
        dueDate: "2024-12-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P002",
    projectName: "Mobile App Development",
    status: "Pending",
    health: "N/A",
    projectManager: "Bob Smith",
    teams: ["Software", "QA", "Design"],
    description: "Developing a mobile app for iOS and Android platforms.",
    plannedStartDate: "2024-08-01",
    plannedEndDate: "2025-02-28",
    actualStartDate: null,
    actualEndDate: null,
    client: "XYZ Corporation",
    contactPerson: "Emily Brown",
    contactPersonPhone: "987-654-3210",
    contactPersonEmail: "emily@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Requirement Gathering",
        description: "Collect user requirements for the mobile app.",
        dueDate: "2024-09-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Design Phase",
        description: "Create UI/UX designs for the mobile app.",
        dueDate: "2024-10-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Development Phase",
        description: "Develop the mobile app features.",
        dueDate: "2025-01-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Testing and Deployment",
        description: "Perform testing and deploy the app to app stores.",
        dueDate: "2025-02-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P003",
    projectName: "Database Migration",
    status: "In Progress",
    health: "Good",
    projectManager: "Eva Garcia",
    teams: ["Software", "Database", "QA"],
    description: "Migrating database from MySQL to PostgreSQL.",
    plannedStartDate: "2024-07-01",
    plannedEndDate: "2024-12-31",
    actualStartDate: "2024-07-15",
    actualEndDate: null,
    client: "123 Corporation",
    contactPerson: "Michael Davis",
    contactPersonPhone: "555-123-4567",
    contactPersonEmail: "michael@example.com",
    history: ["Project kickoff meeting held on 2024-07-10."],
    milestones: [
      {
        milestoneId: "m1",
        name: "Analysis and Planning",
        description:
          "Analyze current database structure and plan migration strategy.",
        dueDate: "2024-08-15",
        status: "Completed",
        tasks: [
          {
            taskId: "t1",
            name: "Database schema analysis",
            description: "Analyze the structure of the current MySQL database.",
            assignedTo: "Database",
            status: "Completed",
            dueDate: "2024-07-30",
          },
          {
            taskId: "t2",
            name: "Migration strategy planning",
            description:
              "Plan the migration strategy from MySQL to PostgreSQL.",
            assignedTo: "Software",
            status: "Completed",
            dueDate: "2024-08-05",
          },
        ],
      },
      {
        milestoneId: "m2",
        name: "Data Migration",
        description: "Migrate data from MySQL to PostgreSQL.",
        dueDate: "2024-10-15",
        status: "In Progress",
        tasks: [
          {
            taskId: "t3",
            name: "Data extraction",
            description: "Extract data from MySQL database.",
            assignedTo: "Database",
            status: "In Progress",
            dueDate: "2024-09-15",
          },
          {
            taskId: "t4",
            name: "Data transformation",
            description: "Transform data to match PostgreSQL schema.",
            assignedTo: "Database",
            status: "Pending",
            dueDate: "2024-09-30",
          },
        ],
      },
      {
        milestoneId: "m3",
        name: "Testing Phase",
        description: "Perform testing on the migrated database.",
        dueDate: "2024-11-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Deployment",
        description: "Deploy the migrated database to production environment.",
        dueDate: "2024-12-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P004",
    projectName: "Product Launch",
    status: "Pending",
    health: "N/A",
    projectManager: "David Lee",
    teams: ["Marketing", "Sales", "PR"],
    description: "Launching a new product in the market.",
    plannedStartDate: "2024-09-01",
    plannedEndDate: "2025-03-31",
    actualStartDate: null,
    actualEndDate: null,
    client: "XYZ Corporation",
    contactPerson: "Sarah Johnson",
    contactPersonPhone: "555-987-6543",
    contactPersonEmail: "sarah@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Market Research",
        description:
          "Conduct market research to identify target audience and competitors.",
        dueDate: "2024-10-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Product Development",
        description:
          "Develop the new product based on market research findings.",
        dueDate: "2025-01-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Marketing Campaign",
        description:
          "Plan and execute marketing campaigns to promote the new product.",
        dueDate: "2025-02-28",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Product Launch Event",
        description:
          "Organize and conduct a launch event to introduce the new product to the market.",
        dueDate: "2025-03-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P005",
    projectName: "Supply Chain Optimization",
    status: "Pending",
    health: "N/A",
    projectManager: "Sophia Patel",
    teams: ["Logistics", "Operations", "IT"],
    description:
      "Optimizing supply chain processes to improve efficiency and reduce costs.",
    plannedStartDate: "2024-10-01",
    plannedEndDate: "2025-04-30",
    actualStartDate: null,
    actualEndDate: null,
    client: "ACME Corporation",
    contactPerson: "James Miller",
    contactPersonPhone: "555-789-1234",
    contactPersonEmail: "james@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Process Analysis",
        description:
          "Analyze current supply chain processes and identify areas for improvement.",
        dueDate: "2024-11-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Technology Evaluation",
        description: "Evaluate IT solutions for supply chain optimization.",
        dueDate: "2025-01-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Implementation",
        description: "Implement selected solutions and technologies.",
        dueDate: "2025-03-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Testing and Optimization",
        description:
          "Test implemented solutions and optimize processes for maximum efficiency.",
        dueDate: "2025-04-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P006",
    projectName: "Employee Training Program",
    status: "Pending",
    health: "N/A",
    projectManager: "Michael Brown",
    teams: ["HR", "Training"],
    description:
      "Developing and implementing a comprehensive training program for employees.",
    plannedStartDate: "2024-11-01",
    plannedEndDate: "2025-05-31",
    actualStartDate: null,
    actualEndDate: null,
    client: "Company ABC",
    contactPerson: "Lisa Wilson",
    contactPersonPhone: "555-456-7890",
    contactPersonEmail: "lisa@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Training Needs Assessment",
        description:
          "Assess training needs of employees and identify areas for improvement.",
        dueDate: "2024-12-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Curriculum Development",
        description:
          "Develop training materials and curriculum based on identified needs.",
        dueDate: "2025-02-28",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Training Delivery",
        description: "Deliver training sessions to employees.",
        dueDate: "2025-04-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Evaluation and Feedback",
        description:
          "Evaluate training effectiveness and gather feedback for improvement.",
        dueDate: "2025-05-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P007",
    projectName: "New Product Development",
    status: "Pending",
    health: "N/A",
    projectManager: "Sophie Wilson",
    teams: ["R&D", "Design", "Manufacturing"],
    description: "Developing a new product line to expand market presence.",
    plannedStartDate: "2025-01-01",
    plannedEndDate: "2025-07-31",
    actualStartDate: null,
    actualEndDate: null,
    client: "Company XYZ",
    contactPerson: "Michael Thompson",
    contactPersonPhone: "555-789-4567",
    contactPersonEmail: "michael@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Conceptualization",
        description: "Generate ideas and concepts for new product development.",
        dueDate: "2025-02-28",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Product Design",
        description: "Design the new product based on selected concept.",
        dueDate: "2025-04-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Prototype Development",
        description: "Build prototypes for testing and validation.",
        dueDate: "2025-06-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Manufacturing Setup",
        description: "Set up manufacturing processes for mass production.",
        dueDate: "2025-07-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P008",
    projectName: "Website Security Enhancement",
    status: "Pending",
    health: "N/A",
    projectManager: "Emma White",
    teams: ["IT", "Security"],
    description:
      "Enhancing security measures to protect company website from cyber threats.",
    plannedStartDate: "2025-02-01",
    plannedEndDate: "2025-08-31",
    actualStartDate: null,
    actualEndDate: null,
    client: "Company XYZ",
    contactPerson: "David Miller",
    contactPersonPhone: "555-321-9876",
    contactPersonEmail: "david@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Security Assessment",
        description:
          "Assess current security measures and identify vulnerabilities.",
        dueDate: "2025-03-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Security Policy Development",
        description:
          "Develop security policies and procedures to address identified vulnerabilities.",
        dueDate: "2025-05-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "Implementation",
        description: "Implement security measures and policies.",
        dueDate: "2025-07-15",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Testing and Optimization",
        description:
          "Test implemented security measures and optimize for effectiveness.",
        dueDate: "2025-08-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P009",
    projectName: "Customer Relationship Management (CRM) Implementation",
    status: "Pending",
    health: "N/A",
    projectManager: "Olivia Jones",
    teams: ["IT", "Sales", "Customer Service"],
    description:
      "Implementing a CRM system to streamline customer interactions and improve customer satisfaction.",
    plannedStartDate: "2025-03-01",
    plannedEndDate: "2025-09-30",
    actualStartDate: null,
    actualEndDate: null,
    client: "Company ABC",
    contactPerson: "Emily Davis",
    contactPersonPhone: "555-456-1234",
    contactPersonEmail: "emily@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "Requirements Gathering",
        description: "Gather requirements for CRM system from stakeholders.",
        dueDate: "2025-04-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "System Selection",
        description: "Select CRM system vendor based on gathered requirements.",
        dueDate: "2025-06-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "System Implementation",
        description:
          "Implement selected CRM system and customize as per requirements.",
        dueDate: "2025-08-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Training and Adoption",
        description:
          "Provide training to users and ensure smooth adoption of CRM system.",
        dueDate: "2025-09-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  {
    projectId: "P010",
    projectName: "Financial System Upgrade",
    status: "Pending",
    health: "N/A",
    projectManager: "Noah Clark",
    teams: ["Finance", "IT"],
    description:
      "Upgrading the company's financial system to improve efficiency and compliance.",
    plannedStartDate: "2025-04-01",
    plannedEndDate: "2025-10-31",
    actualStartDate: null,
    actualEndDate: null,
    client: "Company XYZ",
    contactPerson: "Sophia Brown",
    contactPersonPhone: "555-987-6543",
    contactPersonEmail: "sophia@example.com",
    history: [],
    milestones: [
      {
        milestoneId: "m1",
        name: "System Assessment",
        description:
          "Assess current financial system and identify areas for improvement.",
        dueDate: "2025-05-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m2",
        name: "Vendor Selection",
        description: "Select vendor for new financial system implementation.",
        dueDate: "2025-07-31",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m3",
        name: "System Implementation",
        description: "Implement new financial system and migrate data.",
        dueDate: "2025-09-30",
        status: "Pending",
        tasks: [],
      },
      {
        milestoneId: "m4",
        name: "Testing and Training",
        description: "Test new system and provide training to users.",
        dueDate: "2025-10-15",
        status: "Pending",
        tasks: [],
      },
    ],
  },
  // Add more projects here...
];

export default projectDataWithMilestones;
